name: GitHub Action Lint

on:
  push:
    paths:
      - ".github/**/*.yml"
      - ".github/**/*.yaml"

jobs:
  actionlint:
    name: Actionlint
    runs-on: ubuntu-slim
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          persist-credentials: false
      - name: lint
        run: |
          bash <(curl https://raw.githubusercontent.com/rhysd/actionlint/v1.7.12/scripts/download-actionlint.bash)
          ./actionlint
        shell: bash
